version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/code
    command: uvicorn catalog_api.main:app --host 0.0.0.0 --port 80 --reload

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
