FROM python:3.10
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./catalog_api /code/catalog_api
CMD ["pytest", "-p", "no:warnings"]
